name = "pages-template"
compatibility_date = "2024-01-01"
account_id = "d2b8c5524b7259214fa302f1fecb4ad6"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "ecommerce-db"
database_id = "d689668f-4056-4309-af34-ca2331bb1f2c"

# 환경 변수 (선택사항)
[vars]
ENVIRONMENT = "production"
